spring.application.name=demo

server.port=8090

spring.datasource.url=jdbc:sqlite:movies.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

app.security.default-user.name=admin
app.security.default-user.password=admin123

# TMDB 
tmdb.api-key=db44800cadd0baa04905bac6251520e1
tmdb.base-url=https://api.themoviedb.org/3 
